### Listar todos os clientes
GET http://localhost:3000/clientes

### Listar todos os carros
GET http://localhost:3000/carros

### Listar todos os vendedores
GET http://localhost:3000/vendedores

###
# ==================================
#       SERVIÇO DE RELATÓRIOS
# ==================================
###

### Relatório de carros
GET http://localhost:4000/relatorio/carros

### Relatório de Vendas
GET http://localhost:4000/relatorio/vendas